"""
Theme definitions for the Draft Survey Application.
"""

dark_theme = {
    "name": "dark",
    "notebook_bg": "black",
    "tab_bg": "black",
    "tab_fg": "black",
    "tab_selected_bg": "gray35",
    "tab_active_bg": "gray25",
    "tab_selected_fg": "gold",
    "tab_active_fg": "light blue",
    "frame_bg": "gray15",
    "labelframe_bg": "gray15",
    "labelframe_fg": "gold",
    "button_bg": "gray25",
    "button_fg": "black",
    "button_active_bg": "gray35",
    "button_pressed_bg": "gray20",
    "button_active_fg": "white",
    "entry_bg": "gray10",
    "entry_fg": "white",
    "entry_insert": "white",
    "label_fg": "white",
    "recap_label_bg": "gray15",
    "recap_label_fg": "white",
    "cargo_label_fg": "cyan",
    "diff_label_fg": "orange red",
    "text_bg": "black",
    "text_fg": "light green",
    "title_bg": "gray12",
    "title_fg": "gold",
    "labeled_entry_label_bg": "gray15",
    "labeled_entry_label_fg": "gold",
}

light_theme = {
    "name": "light",
    "notebook_bg": "white",
    "tab_bg": "light gray",
    "tab_fg": "black",
    "tab_selected_bg": "white",
    "tab_active_bg": "#E0E0E0",
    "tab_selected_fg": "blue",
    "tab_active_fg": "dark blue",
    "frame_bg": "#F0F0F0",
    "labelframe_bg": "#F0F0F0",
    "labelframe_fg": "black",
    "button_bg": "#E0E0E0",
    "button_fg": "black",
    "button_active_bg": "#D0D0D0",
    "button_pressed_bg": "#C0C0C0",
    "button_active_fg": "black",
    "entry_bg": "white",
    "entry_fg": "black",
    "entry_insert": "black",
    "label_fg": "black",
    "recap_label_bg": "#F0F0F0",
    "recap_label_fg": "black",
    "cargo_label_fg": "navy",
    "diff_label_fg": "red",
    "text_bg": "white",
    "text_fg": "black",
    "title_bg": "#E0E0E0",
    "title_fg": "black",
    "labeled_entry_label_bg": "#F0F0F0",
    "labeled_entry_label_fg": "black",
}
